### PR TITLE
Fix #577

### LINKED ISSUE #577: [config-presets/html-standard]  a lot of `character-reference` error for non-existent characters
- Markuplint version: `3.0.0-alpha.5`
- Parser lang: HTML 
- Node.js version: `16.16.0`
- OS: Windows

## Describe the bug

`markuplint:html-standard` reports a lot of `character-reference` error, but these characters don't exist.

## Code Example

HTML (`sample.html`)

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  sample
</body>
</html>
```

Config:

```
module.exports = {
  extends: ["markuplint:html-standard"],
};
```

Output:

```
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:10:8
   9: </body>
  10: </html><
  11:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:10:22
   9: </body>
  10: </html>>
  11:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:11:1
  10: </html>
  11: <
  12:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:11:6
  10: </html>
  11: >
  12:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:12:1
  11:
  12: <
  13:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:12:6
  11:
  12: >
  13:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:13:3
  12:
  13: <
  14:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:13:17
  12:
  13: "
  14:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:13:23
  12:
  13: "
  14:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:13:24
  12:
  13: >
  14:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:14:3
  13:
  14: <
  15:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:14:9
  13:
  14: >
  15:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:14:18
  13:
  14: <
  15:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:14:25
  13:
  14: >
  15:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:15:1
  14:
  15: <
  16:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:15:7
  14:
  15: >
  16:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:16:1
  15:
  16: <
  17:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:16:6
  15:
  16: >
  17:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:18:1
  17:
  18: <
  19:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:18:7
  17:
  18: >
  19:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:19:1
  18:
  19: <
  20:
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:19:7
  18:
  19: >
  20:
```

sample.html has only 10 lines, but there is an error for line 19 ...

## The current behavior

Reports a lot of `character-reference` error.

## The expected behavior

Reports no errors

### PR DESCRIPTION
**Pull request by YusukeHirao**
Fixes #577 

## What is the purpose of this PR?

- [x] Fix bug
- [ ] Fix typo
- [ ] Update specs
- [ ] Add new rule
- [ ] Add new parser
- [ ] Improve or refactor rules
- [ ] Add a new core feature
- [ ] Improve or refactor core features
- [ ] Update documents
- [ ] Others

### Description

[WIP] Added test cases only.

## Checklist

Fill out the checks for the applicable purpose.

- [ ] Fix bug
  - [ ] Add the test that can check whether resolved the issue.
- [ ] Update specs
  - [ ] Element
    - [ ] Update **[global attributes](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/html-spec/src/spec-common.attributes.json)**
    - [ ] Update **[content models](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/html-spec/src/spec-common.contents.json)**
    - [ ] Add also ARIA that you explored **ARIA in HTML [Recommendation](https://www.w3.org/TR/html-aria/) and [Editor's draft](https://w3c.github.io/html-aria/)**
  - [ ] Attribute
    - [ ] Update **[global attributes](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/html-spec/src/spec-common.attributes.json)**
    - [ ] Update **[IDL attribute](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/parser-utils/src/idl-attributes.ts)**
- [ ] Add new rule
  - [ ] Add a test
  - [ ] Add a README document
    - [ ] Create an issue that requests translating the doc if you want.
  - [ ] Add to [index](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/rules/src/index.ts)
  - [ ] Add JSON schema to [schema.json](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/rules/schema.json)
  - [ ] Add to [initializer](https://github.com/markuplint/markuplint/blob/main/packages/markuplint/src/cli/init/index.ts)
  - [ ] Add to [`@markuplint/config-presets`](https://github.com/markuplint/markuplint/tree/main/packages/%40markuplint/config-presets)
- [ ] Add new parser
  - [ ] Add a test
    - [ ] Do a test with some parser.
  - [ ] Add to [initializer](https://github.com/markuplint/markuplint/blob/main/packages/markuplint/src/cli/init/index.ts)

### CODE REVIEW

**Comment by YusukeHirao** [comment]
@kagankan 

I added test cases on #577.
But I didn't detect the problem.

Can you check it in your environment?

**Comment by kagankan** [comment]
@YusukeHirao 

Thank you for dealing with it quickly.

I'll report what I found.

## What I found
- I ran the test code on my Windows, the added tests about `character-reference` succeeded ✅
  - However, there were other failures as automated test shows 
    - https://github.com/markuplint/markuplint/actions/runs/3565573637/jobs/5990911071
    - But it doesn't matter in this issue.
- I tried some patterns, I found that this problem occurs only "when I updated markuplint in existing project"
  - This may be the matter of dependencies, I guess.

## Steps to reproduce

I couldn't find out the real cause of it, but I could reproduce the problem.

### Environment

- Windows 10
- node v16.16.0
- npm 8.12.1

### 1. make a directory like this

```
.
|-- .markuplintrc.js
|-- package.json
|-- sample.html
```

#### .markuplintrc.js

```
module.exports = {
    "extends": ["markuplint:recommended"]
}
```

#### package.json

```
{
  "name": "sample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "lint": "markuplint sample.html"
  },
  "dependencies": {
    "@astrojs/tailwind": "^2.1.2",
    "astro": "^1.6.0",
    "autoprefixer": "^10.4.13",
    "destyle.css": "^4.0.0",
    "gsap": "^3.11.3",
    "sass": "^1.56.1",
    "tailwindcss": "^3.2.4",
    "typescript": "^4.9.3"
  },
  "devDependencies": {
    "@markuplint/astro-parser": "^2.2.2",
    "@typescript-eslint/eslint-plugin": "^5.42.1",
    "@typescript-eslint/parser": "^5.42.1",
    "eslint": "^8.27.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-astro": "^0.21.0",
    "eslint-plugin-import": "^2.26.0",
    "markuplint": "^2.11.2",
    "postcss-html": "^1.5.0",
    "prettier": "^2.7.1",
    "scaffdog": "^2.4.0",
    "stylelint": "^14.14.1",
    "stylelint-config-html": "^1.1.0",
    "stylelint-config-prettier": "^9.0.4",
    "stylelint-config-recess-order": "^3.0.0",
    "stylelint-config-recommended-scss": "^8.0.0"
  }
}
```

**Point:**
`"markuplint": "^2.11.2",`

markuplint is v2 at this point.

#### sample.html

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  sample
</body>
```


### 2. install packages

```
npm install
```

### 3. lint (it is expected behavior at this point)

```
npm run lint
```

→`character-reference` error doesn't appear. 
(this is expected behavior ✅)

```
<markuplint> error: 要素「html」には属性「lang」が必要です (required-attr) C:\Users\xxx\sample.html:2:1
  1: <!DOCTYPE•html>
  2: <html>
  3: <head>
<markuplint> error: 要素「h1」が必要です (required-h1) C:\Users\xxx\sample.html:1:1
  1: <!DOCTYPE•html>
  2: <html>
```

### 4. update markuplint

```
npm i markuplint@next
```

### 5. lint (the problem happens here!)

```
npm run lint
```

→`character-reference` errors appeared. ❌

```
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:9:8
   8: ••sample
   9: </body><
  10: 
<markuplint> error: 不正な文字は文字参照でエスケープするべきです (character-reference) C:\Users\xxx\sample.html:9:22
   8: ••sample
   9: </body>>
  10: 

// many character-reference errors
// ...
```

It was same when I use `yarn`


### 6. (Additional investigation) 

1. Delete `node_modules` directory and `package-lock.json` file.
2. Exec `npm install`

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @markuplint/config-presets@3.0.0-alpha.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Owner\AppData\Local\npm-cache\_logs\2022-11-28T17_04_12_746Z-debug-0.log
```

installation error occured 🤔

Did I do something wrong operation ...?

**Comment by YusukeHirao** [comment]
@kagankan 

Sorry, my explanation was terrible.

Could you pull this PR to your local and run it on this repository?
I got ready the test codes for you to run.

**Comment by kagankan** [comment]
@YusukeHirao 

I'm sorry. My explanation was also terrible.

1.  I pulled this PR to my local and ran it.
2. The test codes you added were successful.
3. Therefore, the implementation is correct.

I looked into the reason why I got the bug.
I'll report it on #577 later

**Pull request closed without merging**
