### PR TITLE
`no-refer-to-non-existent-id` supports fragment

### LINKED ISSUE #649: Supporting for detection of `a[href^="#"]` referring to non existent id
`no-refer-to-non-existent-id` rule warns only `for` or `aria-` attributes.

I hope the rule warns the code below:

```html
<a href="#main">To main</a>
<!-- No `main` ID -->
```

Correct examples:

```html
<a href="#main">To main</a>
<main id="main"></main>
```

```html
<a href="/other-page/#main">To other page</a>
```

The codes below will be always correct according to the spec.
https://html.spec.whatwg.org/multipage/browsing-the-web.html#scrolling-to-a-fragment

>If fragment is the empty string, then return the special value top of the document.

```html
<a href="#">To top</a>
```

>If decodedFragment is an ASCII case-insensitive match for the string top, then return the top of the document.

```html
<a href="#top">To top</a>
```

---

(edit)

After posting, I remembered `name` attribute was "obsolete but conforming"...
https://html.spec.whatwg.org/multipage/obsolete.html#obsolete-but-conforming-features

```html
<a href="#main">To main</a>
<a name="main"></a>
```

So this code should also be treated as correct code.
(Of course, `deprecated-attr` rule warns this, but the href's reference is correct.)
Maybe this feature will beyond the scope of no-refer-to-non-existent-_id_ ...? 🤔

### PR DESCRIPTION
**Pull request by YusukeHirao**
Fixes #649

## What is the purpose of this PR?

- [ ] Fix bug
- [ ] Fix typo
- [ ] Update specs
- [ ] Add new rule
- [ ] Add new parser
- [x] Improve or refactor rules
- [ ] Add a new core feature
- [ ] Improve or refactor core features
- [ ] Update documents
- [ ] Others

## Checklist

Fill out the checks for the applicable purpose.

- [ ] Fix bug
  - [ ] Add the test that can check whether resolved the issue.
- [ ] Update specs
  - [ ] Element
    - [ ] Update **[global attributes](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/html-spec/src/spec-common.attributes.json)**
    - [ ] Update **[content models](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/html-spec/src/spec-common.contents.json)**
    - [ ] Add also ARIA that you explored **ARIA in HTML [Recommendation](https://www.w3.org/TR/html-aria/) and [Editor's draft](https://w3c.github.io/html-aria/)**
  - [ ] Attribute
    - [ ] Update **[global attributes](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/html-spec/src/spec-common.attributes.json)**
    - [ ] Update **[IDL attribute](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/parser-utils/src/idl-attributes.ts)**
- [ ] Add new rule
  - [ ] Add a test
  - [ ] Add a README document
    - [ ] Create an issue that requests translating the doc if you want.
  - [ ] Add to [index](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/rules/src/index.ts)
  - [ ] Add JSON schema to [schema.json](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/rules/schema.json)
  - [ ] Add to [initializer](https://github.com/markuplint/markuplint/blob/main/packages/markuplint/src/cli/init/index.ts)
  - [ ] Add to [`@markuplint/config-presets`](https://github.com/markuplint/markuplint/tree/main/packages/%40markuplint/config-presets)
- [ ] Add new parser
  - [ ] Add a test
    - [ ] Do a test with some parser.
  - [ ] Add to [initializer](https://github.com/markuplint/markuplint/blob/main/packages/markuplint/src/cli/init/index.ts)

### CODE REVIEW

**Comment by YusukeHirao** [comment]
@kagankan 

Can you just check the test?

**Comment by YusukeHirao** [comment]
I forgot it ignores the "top" keyword. I'll implement it.

**Comment by YusukeHirao** [comment]
> I forgot it ignores the "top" keyword. I'll implement it.

Done.

**Comment by kagankan** [comment]
@YusukeHirao 

Thank you for working on this!!

I ran the test code and also checked it manually.
I confirmed that it is working as expected! 👍👍👍 

It will make our coding more peaceful 😊

**Pull request merged**
