### PR TITLE
refine japnanese error message

### PR DESCRIPTION
**Pull request by conao3**
Hi, I refine japanese error message.

"上げる" have double meaning, users may confuse.

```
インデントを上げる -> インデントを深くする
インデントを下げる -> インデントを浅くする
```

"上げる" means "up" and "increase", users may misunderstand to
tend to remove some indentation but we want to suggest adding
some it.

The fact is, Code blocks are shallower and indentation levels are
reduced.

"深くする" means "make one deeper", users should understand to
add some indentation.

---

In [update PowerPoint 2007 to 2010](https://hamachan.info/win7/PowerPoint/indent.html), Microsoft changes expression;
"インデントを上げる" to "インデントを増やす".

But I think "インデントを深くする" is better expression because
it has simple one meanings; as we develop linter.

### CODE REVIEW

**Comment by conao3** [comment]
> /bin/sh: 1: lerna: not found

why?

**Comment by conao3** [comment]
build on ubuntu earlier, build on macos is canceled.  It is a not better situation I think.

**Comment by conao3** [comment]
rebase branch

**Comment by YusukeHirao** [comment]
@conao3 Thank you, and I merge.

**Pull request merged**
