### PR TITLE
Added the GCC error message format.

### PR DESCRIPTION
**Pull request by YusukeHirao**
For #86

### CODE REVIEW

**Comment by YusukeHirao** [comment]
@conao3

Is that format correct below?

```
002.html:line2.column7: 属性値はダブルクオーテーションで囲うべきです
002.html:line4.column8: 属性値はダブルクオーテーションで囲うべきです
002.html:line5.column8: 属性値はダブルクオーテーションで囲うべきです
002.html:line5.column22: 属性値はダブルクオーテーションで囲うべきです
002.html:line6.column8: 属性値はダブルクオーテーションで囲うべきです
002.html:line6.column35: 属性値はダブルクオーテーションで囲うべきです
```

Is the format correct below?
Do you need the end-line number and end-column?

**Comment by conao3** [comment]
That link I suggested is GNU Coding Standards' error format and it seems *minimum* error format.
please refer gcc output.
```sh
$ gcc ansi.c -Wall
ansi.c: In function ‘main’:
ansi.c:7:15: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
    7 |   for (i = 0; i = 100; i++) {
      |               ^
ansi.c:9:27: error: expected ‘;’ before ‘}’ token
    9 |       fprintf(stderr, "#")
      |                           ^
      |                           ;
   10 |     }
      |     ~                      
ansi.c:11:12: warning: passing argument 1 of ‘printf’ from incompatible pointer type [-Wincompatible-pointer-types]
   11 |     printf(stderr, "\n");
      |            ^~~~~~
      |            |
      |            FILE *
In file included from ansi.c:1:
/usr/include/stdio.h:332:43: note: expected ‘const char * restrict’ but argument is of type ‘FILE *’
  332 | extern int printf (const char *__restrict __format, ...);
```
and clean output,
```
$ gcc ansi.c -Wall
ansi.c: In function ‘main’:
ansi.c:7:15: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
ansi.c:9:27: error: expected ‘;’ before ‘}’ token     
ansi.c:11:12: warning: passing argument 1 of ‘printf’ from incompatible pointer type [-Wincompatible-pointer-types]
In file included from ansi.c:1:
/usr/include/stdio.h:332:43: note: expected ‘const char * restrict’ but argument is of type ‘FILE *’
  332 | extern int printf (const char *__restrict __format, ...);
```

So, you can use `warning: ` and `error: ` label to express the error level and remove `line` and `column`.

**Comment by YusukeHirao** [comment]
@conao3
I see. Thank you for your review.
I'll improve it.

**Comment by YusukeHirao** [comment]
@conao3 

Is this output you expected?

```sh
$ yarn cli -f gcc ./test/fixture/003.html

003.html:29:30: error: 不正な文字は参照文字でエスケープするべきです [character-reference]
003.html:29:31: error: 不正な文字は参照文字でエスケープするべきです [character-reference]
003.html:29:33: error: 不正な文字は参照文字でエスケープするべきです [character-reference]
003.html:38:21: error: align属性は廃止ずみです [deprecated-attr]
003.html:33:2: error: 要素は非推奨です [deprecated-element]
003.html:1:1: error: 廃止された文書型を宣言しないでください [doctype]
003.html:22:9: error: id属性の値が重複しています [id-duplication]
003.html:40:1: warning: インデントはタブにしてください [indentation]
003.html:54:1: warning: インデントを下げてください [indentation]
003.html:55:1: warning: インデントはスペースにしてください [indentation]
```

Could you tell me a reason you need non-minimum output?
If you want to parse it, I think you should use the JSON format.

**Comment by conao3** [comment]
error message is japanese as a default?
Most users expect error message is english so how we get english error message?

> Could you tell me a reason you need non-minimum output?
If you want to parse it, I think you should use the JSON format.

This format is not _non-mimimum output_ I think, but this format is well-known format to express error information.
On the Emacs side, if markuplint outputs error message like a gcc format, we can use the information with a bit specification.

In generally, one information in one line is most important thing in *nix tool. This enables us easy to use the output with corporate other tools.
for example, `markuplint {{file}}.html | wc -l` to get count of error/warnings.

**Comment by conao3** [comment]
Oh, I see. The *minimum/non-minimum output* issue comes from this my comment?

> That link I suggested is GNU Coding Standards' error format and it seems minimum error format.
please refer gcc output.

It's a simple idea, because if markuplint can produce the same information that gcc produces, I want it to be in the same format.

**Comment by YusukeHirao** [comment]
@conao3 

First, The message is output in locale language on OS.
It has an option "locale" in API but has not in CLI, So I'll create the issue. Thank you for making me realize.

And I could not search about that detailed format.
If you know,  please tell me the official document and/or the official specs about the format?
I want that because I must responsible for testing for the output and code.

You may think so I'm dependent but I want your help.

**Comment by conao3** [comment]
I can't spec for gcc output too. I think gcc outputs message include *labels* and *kind of error* as a message.
So some tools which exprect strict gcc coding standards' format parses `ansi.c:7:15: warning: suggest parentheses around assignment used as truth value [-Wparentheses]` to [`ansi.c`, `7`, `15`, `warning: suggest parentheses around assignment used as truth value [-Wparentheses]`] but there're no issues I think.

**Pull request closed without merging**
