### PR TITLE
Write the contributing.md

### PR DESCRIPTION
**Pull request by YusukeHirao**
For #104 
I wrote the necessary bare minimum.

### CODE REVIEW

**Comment by YusukeHirao** [comment]
@conao3 @tyankatsu0105 
Please review this.

**Comment by yamashita-optarc** [comment]
I think it is good!

**Comment by conao3** [comment]
I think this is good!

**Comment by YusukeHirao** [comment]
@conao3 
Thanks! Could you approve?

**Review by conao3 — APPROVED** [review]

**Pull request merged**
