### PR TITLE
Fix path about drive letter for Windows

### LINKED ISSUE #1518: Fix config-error in VS Code extension when project is located non-default drive on Windows
- Markuplint version: `4.2.0`
- Parser lang: HTML
- Node.js version: `20.11.1`
- OS: Windows

## Describe the bug

My VS code extensions are installed on C drive by default.
I created a project folder on D drive.
When I open the folder with VS code, I only get a problem with `Markuplint(config-error)`. Even when I open an HTML file with some Markuplint errors, the problem is only the config-error below.
`ENOENT: no such file or directory, open 'd:\Users\username\.vscode\extensions\yusukehirao.vscode-markuplint-4.2.0\node_modules\@markuplint\config-presets\preset.recommended.json'`

Looking at the log below, I thought it appeared that the cause was that the drive path was also erased when the path was normalized here.
https://github.com/markuplint/markuplint/blob/7f949a0ab488c0045185fa14080c3ce671956afc/packages/%40markuplint/file-resolver/src/force-import-json-in-module.ts#L31-L38

<details>

<summary>log</summary>

```
2024-03-09T05:41:33.280Z markuplint-cli:ml-engine exec: start
2024-03-09T05:41:33.282Z markuplint-cli:ml-engine:config configProvider: ConfigProvider {}
2024-03-09T05:41:33.282Z markuplint-cli:ml-engine:config defaultConfigKey: 0
2024-03-09T05:41:33.284Z ml-fr:config-provider search: d:\markuplint-test\no-error.html
2024-03-09T05:41:33.284Z ml-fr:config-provider isExists: true
2024-03-09T05:41:33.284Z ml-fr:search Search dir: d:\markuplint-test
2024-03-09T05:41:33.358Z ml-fr:search Search result: null
2024-03-09T05:41:33.358Z ml-fr:config-provider searched config: null
2024-03-09T05:41:33.358Z markuplint-cli:ml-engine:config configFilePathsFromTarget: 0
2024-03-09T05:41:33.358Z markuplint-cli:ml-engine:config option.config: N/A
2024-03-09T05:41:33.358Z markuplint-cli:ml-engine:config defaultRecommended: N/A
2024-03-09T05:41:33.364Z ml-fr:force-import-json-in-module Error in forceImportJsonInModule: TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///c:/Users/username/.vscode/extensions/yusukehirao.vscode-markuplint-4.2.0/node_modules/@markuplint/config-presets/preset.recommended.json" needs an import assertion of type "json"
    at new NodeError (node:internal/errors:405:5)
    at validateAssertions (node:internal/modules/esm/assert:95:15)
    at defaultLoad (node:internal/modules/esm/load:86:3)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:603:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at ModuleJob (node:internal/modules/esm/module_job:64:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) {
  code: 'ERR_IMPORT_ASSERTION_TYPE_MISSING'
}
2024-03-09T05:41:33.364Z ml-fr:force-import-json-in-module Extract path: file:///c:/Users/username/.vscode/extensions/yusukehirao.vscode-markuplint-4.2.0/node_modules/@markuplint/config-presets/preset.recommended.json
2024-03-09T05:41:33.364Z ml-fr:force-import-json-in-module Find JSON file path: \Users\username\.vscode\extensions\yusukehirao.vscode-markuplint-4.2.0\node_modules\@markuplint\config-presets\preset.recommended.json
2024-03-09T05:41:33.364Z markuplint-cli:ml-engine:file Fetched Config files: Set(0) {}

2024-03-09 14:41:33.435 [info] 2024-03-09T05:41:33.364Z markuplint-cli:ml-engine:file Resolved Config: {}
2024-03-09T05:41:33.364Z markuplint-cli:ml-engine:file Resolved Plugins: []
2024-03-09T05:41:33.364Z markuplint-cli:ml-engine:file Resolve Errors: [
  [Error: ENOENT: no such file or directory, open 'd:\Users\username\.vscode\extensions\yusukehirao.vscode-markuplint-4.2.0\node_modules\@markuplint\config-presets\preset.recommended.json'] {
    errno: -4058,
    code: 'ENOENT',
    syscall: 'open',
    path: 'd:\\Users\\username\\.vscode\\extensions\\yusukehirao.vscode-markuplint-4.2.0\\node_modules\\@markuplint\\config-presets\\preset.recommended.json'
  }
]
```

</details>

## Steps To Reproduce

on Windows (not tested on Mac)
1. Check where VS code extensions folder(C drive by default).
2. Create a HTML file on another drive.
3. Open it with VS code installed the extension.

## The current behavior
config-error occurs

## The expected behavior
config-error doesn't occur

### PR DESCRIPTION
**Pull request by okathira**
Fixes #1518

## What is the purpose of this PR?

- [x] Fix bug
- [ ] Fix typo
- [ ] Update specs
- [ ] Add new rule
- [ ] Add new parser
- [ ] Improve or refactor rules
- [ ] Add a new core feature
- [ ] Improve or refactor core features
- [ ] Update documents
- [ ] Others

### Description

Make the extension work regardless of which drive the open location is on.

Excuse me, still I have yet to check the extension in real action. Is there way to do it on Windows?

## Checklist

Fill out the checks for the applicable purpose.

- [x] Fix bug
  - [ ] Add the test that can check whether resolved the issue.
- [ ] Update specs
  - [ ] Element
    - [ ] Update **[global attributes](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/html-spec/src/spec-common.attributes.json)**
    - [ ] Update **[content models](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/html-spec/src/spec-common.contents.json)**
    - [ ] Add also ARIA that you explored **ARIA in HTML [Recommendation](https://www.w3.org/TR/html-aria/) and [Editor's draft](https://w3c.github.io/html-aria/)**
  - [ ] Attribute
    - [ ] Update **[global attributes](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/html-spec/src/spec-common.attributes.json)**
    - [ ] Update **[IDL attribute](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/parser-utils/src/idl-attributes.ts)**
- [ ] Add new rule
  - [ ] Add a test
  - [ ] Add a README document
    - [ ] Create an issue that requests translating the doc if you want.
  - [ ] Add to [index](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/rules/src/index.ts)
  - [ ] Add JSON schema to [schema.json](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/rules/schema.json)
  - [ ] Add to [`@markuplint/config-presets`](https://github.com/markuplint/markuplint/tree/main/packages/%40markuplint/config-presets)
    - [ ] And add to [Rulesets of base presets](https://markuplint.dev/docs/guides/presets#rulesets-of-base-presets)
      - [ ] Add to a [doc file](https://github.com/markuplint/markuplint/blob/main/website/docs/guides/presets.md)
      - [ ] Add to a [doc file (ja)](https://github.com/markuplint/markuplint/blob/main/website/i18n/ja/docusaurus-plugin-content-docs/current/guides/presets.md), or create an issue that requests translating the doc if you want.
  - [ ] Add to the [Playground](https://playground.markuplint.dev/)
    - [ ] Add to a [config object](https://github.com/markuplint/markuplint/blob/main/playground/src/ml-playground-home.svelte)
- [ ] Add new parser
  - [ ] Add a test
    - [ ] Do a test with some parser.
  - [ ] Add to [initializer](https://github.com/markuplint/markuplint/blob/main/packages/markuplint/src/cli/init/index.ts)

### CODE REVIEW

**Comment by YusukeHirao** [comment]
@okathira 

Thank you for your contribution!
It seems that the CI tests are failing.
Could you please make the necessary adjustments to your pull request?

**Comment by okathira** [comment]
I created another issue about the CI tests failing https://github.com/markuplint/markuplint/issues/1534

**Comment by YusukeHirao** [comment]
@okathira 
Please merge the latest `dev` branch. The tests will likely run successfully.

**Comment by okathira** [comment]
@YusukeHirao
I rebased and force pushed. Please run the tests.

**Review by YusukeHirao — APPROVED** [review]

**Comment by YusukeHirao** [comment]
@okathira Thank you!

**Pull request merged**
