### PR TITLE
Improve GitHub actions speed

### PR DESCRIPTION
**Pull request by dqn**
Fixes #???

## What is the purpose of this PR?

- [ ] Fix bug
- [ ] Fix typo
- [ ] Update specs
- [ ] Add new rule
- [ ] Add new parser
- [ ] Improve or refactor rules
- [ ] Add a new core feature
- [ ] Improve or refactor core features
- [ ] Update documents
- [x] Others

### Description

- Use Jest shard option
  - https://jestjs.io/ja/docs/next/cli#--shard
- Use actions/cache@v3 to cache node_modules

## Checklist

Fill out the checks for the applicable purpose.

- [ ] Fix bug
  - [ ] Add the test that can check whether resolved the issue.
- [ ] Update specs
  - [ ] Element
    - [ ] Update **[global attributes](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/html-spec/src/spec-common.attributes.json)**
    - [ ] Update **[content models](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/html-spec/src/spec-common.contents.json)**
    - [ ] Add also ARIA that you explored **ARIA in HTML [Recommendation](https://www.w3.org/TR/html-aria/) and [Editor's draft](https://w3c.github.io/html-aria/)**
  - [ ] Attribute
    - [ ] Update **[global attributes](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/html-spec/src/spec-common.attributes.json)**
    - [ ] Update **[IDL attribute](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/parser-utils/src/idl-attributes.ts)**
- [ ] Add new rule
  - [ ] Add a test
  - [ ] Add a README document
    - [ ] Create an issue that requests translating the doc if you want.
  - [ ] Add to [index](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/rules/src/index.ts)
  - [ ] Add JSON schema to [schema.json](https://github.com/markuplint/markuplint/blob/main/packages/%40markuplint/rules/schema.json)
  - [ ] Add to [`@markuplint/config-presets`](https://github.com/markuplint/markuplint/tree/main/packages/%40markuplint/config-presets)
    - [ ] And add to [Rulesets of base presets](https://markuplint.dev/docs/guides/presets#rulesets-of-base-presets)
      - [ ] Add to a [doc file](https://github.com/markuplint/markuplint/blob/main/website/docs/guides/presets.md)
      - [ ] Add to a [doc file (ja)](https://github.com/markuplint/markuplint/blob/main/website/i18n/ja/docusaurus-plugin-content-docs/current/guides/presets.md), or create an issue that requests translating the doc if you want.
  - [ ] Add to the [Playground](https://playground.markuplint.dev/)
    - [ ] Add to a [config object](https://github.com/markuplint/markuplint/blob/main/playground/src/ml-playground-home.svelte)
- [ ] Add new parser
  - [ ] Add a test
    - [ ] Do a test with some parser.
  - [ ] Add to [initializer](https://github.com/markuplint/markuplint/blob/main/packages/markuplint/src/cli/init/index.ts)

### CODE REVIEW

**Comment by dqn** [comment]
I see an error in the installation of dependencies, perhaps due to too many jobs…? I'll try to fix that.

**Comment by dqn** [comment]
In my forked repository, it took 7m 5s for all jobs to complete. This appears to be shorter than in the recent ones.
https://github.com/dqn/markuplint/actions/runs/4839803054

**Comment by dqn** [comment]
It seems that the problem of dependencies failing to install in `windows-latest` is not limited to using the shard option.
https://github.com/markuplint/markuplint/actions/runs/4839598106/jobs/8624719274

However, the number of CPUs on CI machines is not that large, so shards count may remain as they are now.

**Comment by YusukeHirao** [comment]
@dqn 

Thanks for the late-night response. Installation failures on Windows environments happen quite frequently. I'm sorry for having you look into it; it's okay to disregard it. You might want to revert the value back to the initial one.

**Comment by dqn** [comment]
@YusukeHirao 
Ok, I revert shard count.

**Comment by YusukeHirao** [comment]
@dqn 

Thank you. It's definitely faster now. I appreciate your help, including introducing me to `shard`.

**Pull request merged**
