### PR TITLE
use fail-fast false strategy on multi environment test

### PR DESCRIPTION
**Pull request by conao3**
use fail-fast false strategy on multi environment test
This PR fixes situation mentioned https://github.com/markuplint/markuplint/pull/105#issuecomment-717272460

### CODE REVIEW

**Comment by YusukeHirao** [comment]
@conao3 Thanks!

@tyankatsu0105 Could you review this PR?

**Comment by tyankatsu0105** [comment]
Sure.

**Review by tyankatsu0105 — APPROVED** [review]
I don't know about [this option](https://docs.github.com/ja/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) but looks good.

**Comment by YusukeHirao** [comment]
@tyankatsu0105 Thanks!

**Comment by conao3** [comment]
Thanks for merging!

**Pull request merged**
