### PR TITLE
feat: remove unnecessary async/await keywords because sync rules are supported

### PR DESCRIPTION
**Pull request by JounQin**
continue https://github.com/markuplint/markuplint/pull/157#issuecomment-827494898

### CODE REVIEW

**Comment by YusukeHirao** [comment]
Hi @JounQin, Thank you for always!

I'm afraid so, these fixings are resolved in the v3 branch already because I added the rule on ESLint.
Please wait to release the v3, but it will take a while.

**Comment by JounQin** [comment]
OK, so I should contribute no branch `v3` instead.

**Comment by JounQin** [comment]
@YusukeHirao I didn't see them remove at https://github.com/markuplint/markuplint/blob/v3/packages/%40markuplint/rules/src/attr-duplication/index.ts

Is there anything wrong?

**Comment by YusukeHirao** [comment]
Oh, sorry I was wrong.
Umm... I thought that I did.
(Finally, I may have removed the feature branch...)

My bad, for now, I want you PR to the v3 branch.

**Pull request closed without merging**
